services:
  - type: web
    name: soiree-quiz-stephane-marie
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
